### ISSUE TITLE
QA for the chatbot

### ISSUE THREAD

**Issue by CheshtaK** [WooTechnology/ChatBot#3]
Document question-answers for topics such as menstruation, pregnancy, abortion, STDs, depression, anxiety, etc. which would be used to build the chatbot.

For each question and answer there should be atleast 1 or 2 variations present. There should be 10 questions each for the above mentioned topics.

Doc link : [Eliana QA](https://docs.google.com/document/d/1nocw6HwLdcI-TVlho1JjlHF87RbCnZ3qVCS9WV2ZaJw/edit)

**Comment by sachita3** [comment]
[CHATBOT QUESTIONS.docx](https://github.com/WooTechnology/ChatBot/files/4016900/CHATBOT.QUESTIONS.docx)
